
// *** DO NOT EDIT THIS FILE! ***
// This file is generated by Logos processing using Battery_Temperature.xm during each build.

// Logos by Dustin Howett
// See http://iphonedevwiki.net/index.php/Logos
